### ISSUE TITLE
Stripe integration

### ISSUE THREAD

**Issue by jackd0uet** [shofikspace/upskill_saas_tutorial#1]
Hi there,

I am also following this tutorial and have seen that you are ahead of me. I was just wondering if you ran into a problem with your stripe integration. On the new dashboard I cannot find anywhere to customise plan ID so my code is kicking up an error when trying to connect to stripe. I was just wondering if you came across this problem, and if you did how you fixed it?

Cheers,

Jack

**Comment by shofikspace** [comment]
Hi, Same here! I couldn’t' connect Stripe properly. But I didn’t bother much about this issue. It's not like I am building very professional website very soon 😂  its better to finish the lesson and learn about Stripe later. 

Happy learning!

-Shofik

**Comment by jackd0uet** [comment]
Thanks for getting back to me, after a lot of reading it seems like Stripe have moved away from the plans api to a new prices api so I have contacted Rob to let him know. I think I'll choose to do what you did as I am in a very similar situation haha. 

Maybe it would be a good idea to keep in touch if both of us are trying to move into the same field?

Cheers,

Jack

**Comment by shofikspace** [comment]
Ofcourse, we can always discuss about what we are learning next. My email mohammadshofik@gmail.com
